apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zen-gc-leader
data:
  profile: {{ .Values.profile | quote }}
  leader_election: {{ .Values.leaderElection.enabled | quote }}
  namespace: {{ .Release.Namespace | quote }}
