// Code generated by tranche-009 additive compatibility migration. Regenerate
// with controller-gen if the spec/status types change.

// Package v1alpha1 — ZenGCPolicy deep-copy functions mirroring the legacy
// GarbageCollectionPolicy deepcopy (same Spec/Status types).
package v1alpha1

import (
	apimachineryruntime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields of ZenGCPolicy via the shared Spec/Status
// deepcopy implementations.
func (in *ZenGCPolicy) DeepCopyInto(out *ZenGCPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy returns a deep copy of ZenGCPolicy.
func (in *ZenGCPolicy) DeepCopy() *ZenGCPolicy {
	if in == nil {
		return nil
	}
	out := new(ZenGCPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ZenGCPolicy) DeepCopyObject() apimachineryruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields of ZenGCPolicyList.
func (in *ZenGCPolicyList) DeepCopyInto(out *ZenGCPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZenGCPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of ZenGCPolicyList.
func (in *ZenGCPolicyList) DeepCopy() *ZenGCPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZenGCPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ZenGCPolicyList) DeepCopyObject() apimachineryruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
